apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: java-heap-collector
  namespace: moshe-test
  labels:
    k8s-app: java-heap-collector
spec:
  selector:
    matchLabels:
      name: java-heap-collector
  template:
    metadata:
      labels:
        name: java-heap-collector
    spec:
      tolerations:
      - effect: NoSchedule
        operator: Exists
      containers:
      - name: java-heap-collector
        image: 648158488652.dkr.ecr.us-west-2.amazonaws.com/dump-collector:5dd958a-35
        env:
        - name: S3bucket
          value: next-heapdumps
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: dumps
          mountPath: /dumps/
      terminationGracePeriodSeconds: 30
      volumes:
      - name: dumps
        hostPath:
          path: /dumps/
