apiVersion: v1
kind: Pod
metadata:
  labels:
    spotinst.io/restrict-scale-down: true
spec:
  serviceAccount: jenkins-nonadmin-agent-sa
  containers:
    - name: docker
      image: 641202632344.dkr.ecr.us-west-2.amazonaws.com/base_images:maven-base
      imagePullPolicy: Always
      command: ['cat']
      resources:
        limits:
          memory: "1Gi"
          cpu: "2"
        requests:
          memory: "1"
          cpu: "2"
      tty: true
      volumeMounts:
        - mountPath: "/local"
          name: nvme
        - name: dockersock
          mountPath: "/var/run/docker.sock"
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: nvme
      hostPath:
        path: /local
